name = "prado-trocas"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "prado-trocas-db"
database_id = "ae26e687276cddf49fae4e330b4c482d"
migrations_dir = "drizzle"
